### PR TITLE
Support SHA512 authentication

### PR DESCRIPTION
**Pull request by sitingren**
SHA512 implementation without any authentication test add to test suite.

### CODE REVIEW

**Comment by ruojol** [comment]
How do you use this?

**Comment by sitingren** [comment]
@ruojol There are no API change for vertica-python. Please see [Vertica documentation](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/Security/ClientAuth/ConfiguringHashAuthentication.htm) for how to configure SHA512 authentication in your database.

**Comment by ruojol** [comment]
I'm using the vertica-python 0.9.0 package and doing the connection same way as in the guide, but I still get the following error because our DB uses sha512- keys
`encryption algorithm MD5 does not match the effective server configured encryption algorithm SHA512', Sqlstate: b'VX001', Routine: b'password_verify', File: b'/scratch_a/release/svrtar28000/vbuild/vertica/Basics/ClientAuthentication.cpp', Line: b'536', Error Code: b'6429'`
So to rephrase the question do I need to add something to the conn_info dict to make sha512 keys work?

**Comment by sitingren** [comment]
@ruojol Nothing need to be added into conn_info dict. Please upgrade your vertica-python package to 0.9.1 and try again.

**Pull request merged**
