### PR TITLE
Travis CI setup

### PR DESCRIPTION
**Pull request by pachewise**
some changes to be able to run CI on Travis.

### CODE REVIEW

**Comment by sitingren** [comment]
Thank you for your contribution! Would you please tell us how do you test the Travis CI setup? Before merging to master, we need to ensure it works.

**Comment by pachewise** [comment]
@sitingren have it set up here: https://travis-ci.org/pachewise/vertica-python. Once you merge it to master, would recommend setting up this repo in travis-ci.*com* (since they're migrating OSource repos there).

**Comment by sitingren** [comment]
#95 pointed out that it's against the TOS to download and host Vertica packages for public downloading. Everyone need to register and sign in to download Vertica packages, even the free Community Edition. 

We know it is helpful to have CI services, however, we don't want to break the rules. So I'm sorry but I am not able to merge your PR right now because of the Vertica docker container you use. We'll do investigation and hopefully find out a solution soon.

**Comment by pachewise** [comment]
Bummer - let us know what you find.

**Comment by sitingren** [comment]
@pachewise Here's a good piece of news. We got permission to publish a special Vertica Community Edition package (for test only) which would not need you to register. Hopefully, we can figure out how to build a docker container with this package and set up Travis CI over the next couple of weeks. Thanks!

**Comment by pachewise** [comment]
Great news! Thanks for the quick action. Let me know if you need any help with that for this repo.

**Comment by sitingren** [comment]
@pachewise Thank you for your help, I'll merge this PR and tune Travis CI settings in the background.

**Pull request merged**
